apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-wars-api
spec:
  selector:
    matchLabels:
      app: star-wars-api
  template:
    metadata:
      labels:
        app: star-wars-api
    spec:
      containers:
      - name: star-wars-api
        image: guilira/simple-star-wars-api:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
